name: CI build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore KernelMemory.Ecommerce.Sample.sln
      
    - name: Build
      run: dotnet build --no-restore KernelMemory.Ecommerce.Sample.sln

    - name: Check fomatting
      run: dotnet format --verify-no-changes KernelMemory.Ecommerce.Sample.sln
      
    - name: Test
      run: dotnet test --no-build --verbosity normal KernelMemory.Ecommerce.Sample.sln
